name: PRCompile

on:
  pull_request:
    branches: ["main"]
  workflow_dispatch: # Manual trigger added

jobs:
  build-runspace:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
    - name: Compile project
      shell: pwsh
      run: |
        Set-ExecutionPolicy Bypass -Scope Process -Force; ./Compile.ps1
      continue-on-error: false # Directly fail the job on error, removing the need for a separate check
    - name: Run Winutil 
      shell: pwsh
      run: |
        Set-ExectuionPolicy Bypass -Scope Process -Force; ./winutil.ps1
      continue-on-error: false
